### ISSUE TITLE
Ohjelmasivun marginaali pienemmäksi

### ISSUE THREAD

**Issue by Mikael-Lenander** [Mikael-Lenander/vihreiden-ohjelma-alusta#13]
![image](https://github.com/Mikael-Lenander/vihreiden-ohjelma-alusta/assets/65553595/b4a4d178-19f8-4017-8ce2-26d6cb0c44bd)

Ohjelman ja sivuvalikon välissä on erittäin suuri väli. Tee välistä hiukan pienempi. Ohjelmien CSS löytyy kansiosta browser/data-browser/vihreat.

**Comment by jannepeltola** [comment]
Jahka #35 on mergattu, voin lisäillä tämän siihen.
