### ISSUE TITLE
Kun klikkaa hakutuloksesta linkkiä ohjelmaan, scrollaus ei toimi

### ISSUE THREAD

**Issue by jannepeltola** [Mikael-Lenander/vihreiden-ohjelma-alusta#45]
Steps to reproduce:
- Hae "Kulttuuri"
- Valitse ensimmäinen osuma
- Paina "Siirry tekstikohtaan"

Sivu ei skrollaudu oikeaan paikkaan. Kun refreshaa, skrollaus toimii oikein.

**Comment by lippinj** [comment]
Korjattu.
