### ISSUE TITLE
Hakutoiminto antaa välillä outoja tuloksia

### ISSUE THREAD

**Issue by jannepeltola** [Mikael-Lenander/vihreiden-ohjelma-alusta#46]
Hakutoiminto antaa välillä outoja tuloksia.

**puro** antaa:
> Vahvistetaan tutkimuskeskittymiä niin, että suomalaiset korkeakoulut, tutkimuslaitokset ja yritykset pärjäävät entistä paremmin Euroopan unionin TKI-rahoituskilpailussa. Varmistetaan, että hankkeiden EU-rahoitus ei jää kiinni Suomen rahoitusosuuden puuttumisesta.

**testi** antaa:
> Edellytetään suurilta sosiaalisen median alustoilta vihapuhetta torjuvien algoritmien ja moderointikäytäntöjen avoimuutta ja läpinäkyvyyttä. Testataan alustojen moderointikäytäntöjä ja puututaan epäkohtiin sekä kansallisella tasolla että EU:ssa.

**testin** antaa:
> Digitaalisten palveluiden tulee olla saavutettavia. Niissä on huomioitava aistien heikkoudet (tekstin koko, mahdollisuus viestin kuuntelemiseen, videoiden tekstitys) sekä muistiystävällisyys (selkeys ja yksinkertaisuus, ei liian monta porrasta, riittävä opastus).

Onko haussa päällä jonkinlainen Levenshtein distance -logiikka, joka hakee lähiosumia? Ehkä tässä auttaisi osumakohdan korostaminen?

**Comment by lippinj** [comment]
Muutin tämän toistaiseksi olemaan eksakti haku.

**Comment by lippinj** [comment]
Eksakti haku ei tuota "outoja" tuloksia. Tuottaa vähemmän tuloksia ja kaipaa haun parantelua kyllä, mutta se on eri tiketti ;)
