### ISSUE TITLE
Ohjelmakohtien linkit menevät vääriin elementteihin

### ISSUE THREAD

**Issue by jannepeltola** [Mikael-Lenander/vihreiden-ohjelma-alusta#48]
Steps to reproduce:
- Mene osoitteeseen http://localhost:5176/ohjelmat/p9?h=64
- Huomaa, että highlight osuu elementtiin `p9e67`

Nopeasti haarukoituna näyttäisi, että jokainen `ActionList` heittää `ElementInfo`n sisäistä `index`iä yhdellä. `highLightState.index`on OK. En ainakaan välittömästi koodia lukemalla hahmottanut, mistä kiikastaa.

**Comment by lippinj** [comment]
En saa reprodusoitua. Menee oikeaan paikkaan minulla. Olisiko tämä korjautunut jo jossain uudemmista commiteista?

**Comment by jannepeltola** [comment]
Joo, näyttäisi korjaantuneen!
